# Site settings
title: Colegio AnÃ¡huac
email: sebastinlpez@colegionanahuacsc.edu.mx
description: >
  Apuntes diarios del colegionanahuacsc
baseurl: "/colegio_anahuac/" # the subpath of your site, e.g. /blog/
url: "http://sebastianls.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
